http:
  port: 8080

apiEndpoints:
  users:
    paths: '/users/*'
  products:
    paths: '/products/*'
  orders:
    paths: '/orders/*'

serviceEndpoints:
  userService:
    url: 'http://localhost:3001'
  productService:
    url: 'http://localhost:3002'
  orderService:
    url: 'http://localhost:3003'

policies:
  - cors
  - proxy
  - log

pipelines:
  usersPipeline:
    apiEndpoints:
      - users
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService
  productsPipeline:
    apiEndpoints:
      - products
    policies:
      - proxy:
          - action:
              serviceEndpoint: productService
  ordersPipeline:
    apiEndpoints:
      - orders
    policies:
      - proxy:
          - action:
              serviceEndpoint: orderService
